apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: k8s-web-hello
  ports:
   - port: 3030
     targetPort: 3000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.